name: ondre j
favicon: null
layout_spectrum: 0.7952229974325746
typography_spectrum: 0.9523601548280567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4548223565798253
  lightness: 0.16811625729314983
  saturation: 0.9292123522609472
  rhythmicContrast: 0.304187799571082
purpose: []
