name: ondre j
favicon: null
layout_spectrum: 0.7952229974325746
typography_spectrum: 0.9523601548280567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#352333'
    - '#fffffd'
    - '#5a524f'
    - '#b09b7f'
    - '#a06d67'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.9292123522609472
  rhythmicContrast: 0.75
purpose: []
